// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'profile.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'profile.g.dart';

@Freezed(makeCollectionsUnmodifiable: false)
class Profile with _$Profile {
  const factory Profile({
    required String id,
    required String assetImg,
    required String name,
    required List<String> moviesList,
}) = _Profile;

factory Profile.fromJson(Map<String, Object?> json)
=> _$ProfileFromJson(json);
}